Env: World.Environments.DMC.DMC
suite: dmc
env:
    task: walker_run
task_name: walker_run
discrete: false
action_repeat: 2
frame_stack: 3
nstep: 1
train_steps: 1500000
stddev_schedule: 'linear(1.0,0.1,500000)'
hd_capacity: 0


batch_size: 512
