Env: World.Environments.DMC.DMC
suite_name: dmc
env:
    task: walker_stand
task_name: walker_stand
discrete: false
action_repeat: 2
frame_stack: 3
nstep: 1
train_steps: 500000
stddev_schedule: 'linear(1.0,0.1,100000)'
hd_capacity: 0


batch_size: 512
