Env: World.Environments.Datums.Datums
env:
  dataset: ${dataset}
  test_dataset: ${test_dataset}
  low: null
  high: null
  batch_size: ${batch_size}
  num_workers: ${num_workers}
dataset:
  Transform: null
logger:
  log_actions: ${not:${generate}}
suite_name: supervised
task_name: ${format:${dataset._target_}}
train_steps: 200000
stddev_schedule: 'linear(1.0,0.1,100000)'
frame_stack: null
action_repeat: null
nstep: 0
evaluate_per_steps: 1000
evaluate_episodes: 1
learn_per_steps: 1
seed_steps: 0
rand_steps: 0
log_per_epochs: 0
log_per_steps: 300
RL: false
online: false  # Same as offline: true
